/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type UiStrings = {
  _id: string
  _type: 'uiStrings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  notFoundBadge?: string
  notFoundTitle?: string
  notFoundDescription?: string
  notFoundHomeButtonText?: string
  notFoundContactButtonText?: string
  notFoundQuickLinksTitle?: string
  notFoundQuickLinks?: Array<{
    label?: string
    href?: string
    _key: string
  }>
  draftModeLabel?: string
  draftModeExitText?: string
}

export type ConsultingPage = {
  _id: string
  _type: 'consultingPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroBadge?: string
  heroTitle?: string
  heroSubtitle?: string
  heroDescription?: string
  serviceNavItems?: Array<{
    id?: string
    title?: string
    icon?: 'Briefcase' | 'BarChart3' | 'Layers' | 'Shield' | 'Building2' | 'Bitcoin'
    _key: string
  }>
  serviceSections?: Array<{
    id?: string
    icon?: 'Briefcase' | 'BarChart3' | 'Layers' | 'Shield' | 'Building2' | 'Bitcoin'
    title?: string
    description?: Array<string>
    highlight?: string
    iconGradient?: string
    shadowColor?: string
    features?: Array<{
      icon?:
        | 'BarChart3'
        | 'Target'
        | 'TrendingUp'
        | 'Shield'
        | 'Layers'
        | 'Users'
        | 'Map'
        | 'Building2'
        | 'Calculator'
        | 'Dumbbell'
      title?: string
      desc?: string
      _key: string
    }>
    _key: string
  }>
  ctaTitle?: string
  ctaDescription?: string
  ctaButtonText?: string
  ctaButtonHref?: string
  seoTitle?: string
  seoDescription?: string
}

export type MembershipsPage = {
  _id: string
  _type: 'membershipsPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroBadge?: string
  heroTitle?: string
  heroSubtitle?: string
  heroDescription?: string
  heroPrimaryCta?: string
  heroSecondaryCta?: string
  insideSectionTitle?: string
  insideSectionDescription?: string
  insideFeatures?: Array<{
    icon?: 'TrendingUp' | 'Eye' | 'Bell' | 'MessageSquare' | 'GraduationCap'
    text?: string
    _key: string
  }>
  benefitsSectionTitle?: string
  keyBenefits?: Array<{
    icon?: 'Target' | 'Zap' | 'Users' | 'BookOpen' | 'Award'
    title?: string
    description?: string
    _key: string
  }>
  includedSectionTitle?: string
  includedFeatures?: Array<string>
  educationalMiniCourseTitle?: string
  educationalItems?: Array<string>
  additionalIncluded?: Array<string>
  includedTagline?: string
  pricingSectionTitle?: string
  pricingSectionDescription?: string
  plans?: Array<{
    id?: string
    name?: string
    price?: string
    priceValue?: number
    trial?: string
    description?: string
    cta?: string
    popular?: boolean
    stripePriceId?: string
    _key: string
  }>
  popularBadgeText?: string
  accessSectionTitle?: string
  accessSteps?: Array<{
    step?: number
    title?: string
    description?: string
    _key: string
  }>
  accessTagline?: string
  faqSectionTitle?: string
  faqs?: Array<{
    question?: string
    answer?: string
    _key: string
  }>
  comingSoonTitle?: string
  comingSoonDescription?: string
  comingSoonFeatures?: Array<string>
  comingSoonNote?: string
  finalCtaTitle?: string
  finalCtaDescription?: string
  finalCtaButton?: string
  seoTitle?: string
  seoDescription?: string
}

export type ContactPage = {
  _id: string
  _type: 'contactPage'
  _createdAt: string
  _updatedAt: string
  _rev: string
  heroTitle?: string
  heroDescription?: string
  heroHighlight?: string
  introHeading?: string
  introDescription?: string
  introEmailLabel?: string
  introEmail?: string
  formTitle?: string
  formSubtitle?: string
  formSuccessTitle?: string
  formSuccessMessage?: string
  formErrorTitle?: string
  formErrorMessage?: string
  areaOfInterestOptions?: Array<{
    value?: string
    label?: string
    _key: string
  }>
  expectationsHeading?: string
  expectationItems?: Array<{
    icon?: 'UserCheck' | 'Clock' | 'MessageSquare' | 'ShieldCheck'
    text?: string
    _key: string
  }>
  disclaimer?: string
  seoTitle?: string
  seoDescription?: string
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  slug?: Slug
  isHomepage?: boolean
  sections?: Array<
    | ({
        _key: string
      } & HeroSection)
    | ({
        _key: string
      } & WhatWeDoSection)
    | ({
        _key: string
      } & TestimonialCTASection)
    | ({
        _key: string
      } & ThreeCardsSection)
    | ({
        _key: string
      } & RichTextSection)
    | ({
        _key: string
      } & MultiAssetSection)
    | ({
        _key: string
      } & WhyGammaSection)
  >
  seoTitle?: string
  seoDescription?: string
  noIndex?: boolean
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top?: number
  bottom?: number
  left?: number
  right?: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x?: number
  y?: number
  height?: number
  width?: number
}

export type Slug = {
  _type: 'slug'
  current?: string
  source?: string
}

export type SiteSettings = {
  _id: string
  _type: 'siteSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  siteName?: string
  logo?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  logoText?: string
  navItems?: Array<
    {
      _key: string
    } & NavItem
  >
  navCTA?: CtaButton
  mobileSecondaryLinks?: Array<
    {
      _key: string
    } & Link
  >
  mobileFooterText?: string
  footerDescription?: string
  socialLinks?: Array<{
    platform?: 'twitter' | 'linkedin' | 'discord' | 'email'
    url?: string
    _key: string
  }>
  footerColumns?: Array<{
    title?: string
    links?: Array<
      {
        _key: string
      } & Link
    >
    _key: string
  }>
  contactEmail?: string
  copyrightText?: string
  disclaimer?: string
  connectColumnTitle?: string
  seoTitle?: string
  seoDescription?: string
  ogImage?: {
    asset?: {
      _ref: string
      _type: 'reference'
      _weak?: boolean
      [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
    }
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
}

export type CtaButton = {
  _type: 'ctaButton'
  text?: string
  href?: string
  variant?: 'primary' | 'secondary' | 'ghost'
  showArrow?: boolean
}

export type WhyGammaSection = {
  _type: 'whyGammaSection'
  badge?: string
  title?: string
  reasons?: Array<{
    icon?: 'Building' | 'Target' | 'Shield' | 'MessageSquare' | 'Layers'
    text?: string
    _key: string
  }>
}

export type MultiAssetSection = {
  _type: 'multiAssetSection'
  badge?: string
  title?: string
  description?: string
  secondaryDescription?: string
  assetClasses?: Array<{
    icon?: 'TrendingUp' | 'Layers' | 'Globe' | 'Building2' | 'Coins'
    label?: string
    _key: string
  }>
}

export type RichTextSection = {
  _type: 'richTextSection'
  title?: string
  content?: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'normal' | 'h2' | 'h3' | 'h4' | 'blockquote'
        listItem?: 'bullet' | 'number'
        markDefs?: Array<{
          href?: string
          blank?: boolean
          _type: 'link'
          _key: string
        }>
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: {
          _ref: string
          _type: 'reference'
          _weak?: boolean
          [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
        }
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        alt?: string
        caption?: string
        _type: 'image'
        _key: string
      }
  >
  backgroundColor?: 'white' | 'gray' | 'teal'
}

export type ThreeCardsSection = {
  _type: 'threeCardsSection'
  cards?: Array<
    {
      _key: string
    } & ServiceCard
  >
}

export type TestimonialCTASection = {
  _type: 'testimonialCTASection'
  badge?: string
  titleLine1?: string
  titleLine2?: string
  description?: string
  primaryCTA?: CtaButton
  secondaryCTA?: CtaButton
}

export type WhatWeDoSection = {
  _type: 'whatWeDoSection'
  badge?: string
  title?: string
  description?: string
  services?: Array<
    {
      _key: string
    } & ServiceCard
  >
  showViewAllButton?: boolean
  viewAllButtonText?: string
  viewAllButtonHref?: string
}

export type HeroSection = {
  _type: 'heroSection'
  badge?: string
  titleLine1?: string
  titleLine2?: string
  description?: string
  primaryCTA?: CtaButton
  secondaryCTA?: CtaButton
  featureCards?: Array<
    {
      _key: string
    } & ServiceCard
  >
  stats?: Array<
    {
      _key: string
    } & Stat
  >
  bulletPoints?: Array<{
    icon?: 'TrendingUp' | 'Activity' | 'Shield'
    text?: string
    _key: string
  }>
  supportingTagline?: string
}

export type ServiceCard = {
  _type: 'serviceCard'
  icon?: 'BarChart3' | 'Users' | 'Building2' | 'Network' | 'Rocket' | 'Discord'
  title?: string
  description?: string
  href?: string
  linkText?: string
}

export type Stat = {
  _type: 'stat'
  value?: string
  label?: string
}

export type NavItem = {
  _type: 'navItem'
  text?: string
  href?: string
  hasDropdown?: boolean
  dropdownItems?: Array<{
    text?: string
    description?: string
    href?: string
    _key: string
  }>
}

export type Link = {
  _type: 'link'
  text?: string
  href?: string
  isExternal?: boolean
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height?: number
  width?: number
  aspectRatio?: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash?: string
  extension?: string
  mimeType?: string
  size?: number
  assetId?: string
  uploadId?: string
  path?: string
  url?: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | UiStrings
  | ConsultingPage
  | MembershipsPage
  | ContactPage
  | Page
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | SiteSettings
  | CtaButton
  | WhyGammaSection
  | MultiAssetSection
  | RichTextSection
  | ThreeCardsSection
  | TestimonialCTASection
  | WhatWeDoSection
  | HeroSection
  | ServiceCard
  | Stat
  | NavItem
  | Link
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint
export declare const internalGroqTypeReferenceTo: unique symbol
